; LensLife XIAO ESP32-S3R8 firmware (standalone folder)

[platformio]
description = LensLife XIAO ESP32-S3R8 firmware
src_dir = main

[env:xiao-esp32s3r8]
platform = espressif32 @ ~6.10.0
board = seeed_xiao_esp32s3
framework = espidf

board_build.flash_size = 8MB
board_upload.flash_size = 8MB

monitor_speed = 115200
upload_speed = 921600
monitor_rts = 0
monitor_dtr = 0

build_flags =
    -D IDF_IGNORE_GIT_VERSION_CHECK=1
